apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: denyall
spec:
  compiledAdapter: denier
  params:
    status:
      code: 7
      message: Not allowed
---
# The (empty) data handed to denyall at run time
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: denyrequest
spec:
  compiledTemplate: checknothing
---
# The rule that uses denier to deny requests to the guestbook service
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: deny-guestbook
spec:
  match: destination.service.name == "guestbook"
  actions:
  - handler: denyall
    instances:
    - denyrequest
