apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: guestbook-all-v2
  namespace: default
spec:
  appendHeaders:
    hello: world
  destination:
    name: guestbook
  precedence: 1
  route:
  - labels:
      version: "2.0"
